name: Run Selenium Headless and Commit Extract

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  selenium-headless:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Chrome for Selenium
        uses: browser-actions/setup-chrome@v1

      - name: Run Selenium script
        env:
          DISPLAY: :99
        run: |
          python app.py

      - name: Set up authenticated git remote
        if: success()
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.SAMAN_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Commit and push new extracted files
        if: success()
        run: |
          git config user.name "${{ github.actor }}"
          git config --global user.email mdsamanngp@gmail.com
          git add extract/*.csv
          if git diff --cached --quiet; then
            echo "No new files to commit."
          else
            git commit -m "Add new extracted emails file [skip ci]"
            git push
          fi
